### ISSUE TITLE
adding liquidity on IUSD /OUSD with 100 OUSD => 98.7801 IUSDnot liked by the AA

### ISSUE THREAD

**Issue by pascalSAINVITU** [bonustrack/oswap.io#10]
https://explorer.obyte.org/#+fKKHpO65zmZfZrw9KyNCqvOAl8Y2PsJnymyb3l4jAA=
bounced with "error": "wrong ratio of amounts, expected 999999 of V/jyPXbGIoRhfBXCEMP/xzMzaAsYC4oT0RWzJhdJs0Y="
}

**Comment by tarmo888** [comment]
#9 fixed this
